---
version: 2
plan: !include builds/plan.yaml
stages: !include builds/stages.yaml
Build: !include builds/job.yaml

triggers:
- github-trigger:
    repositories:
    - test1

branch-overrides:
  -
    integration-branch1:
      disable-expiry: true
      Build: !include builds/artifact.yaml
  -
    main:
      Build: !include builds/artifact.yaml
  -
    new1:
      disable-expiry: true
  - 
    branch2:
      disable-expiry: true
